<?php

namespace App\Livewire;

use App\Models\NIK;
use App\Models\RelawanManual;
use Filament\Forms;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Livewire\Component;
use Illuminate\Contracts\View\View;

class DaftarForm extends Component implements HasForms
{
    use InteractsWithForms;

    public ?array $data = [];

    public function mount(): void
    {
        $this->form->fill();
    }

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('nik')
                    ->required()
                    ->label('NIK')
                    ->afterStateUpdated(function ($state, callable $set) {
                        if (empty($state)) {
                            $set('name', '');
                            $set('jenis_kelamin', '');
                            $set('kabupaten', '');
                            $set('kecamatan', '');
                            $set('kelurahan', '');
                        } else {
                            $relawan = NIK::where('nik', $state)->first();
                            if ($relawan) {
                                $set('name', $relawan->name);
                                $set('jenis_kelamin', $relawan->jenis_kelamin);
                                $set('kabupaten', $relawan->kabupaten);
                                $set('kecamatan', $relawan->kecamatan);
                                $set('kelurahan', $relawan->kelurahan);
                            }
                        }
                    })
                    ->unique(column: 'nik')
                    ->live(debounce: 500)
                    ->rules([
                        'digits:16',
                    ])
                    ->validationMessages([
                        'unique' => "NIK sudah terdaftar"
                    ]),
                Forms\Components\TextInput::make('name')
                    ->required()
                    ->label('Nama')
                    ->autocapitalize('words')
                    ->dehydrated(true),
                Forms\Components\Select::make('jenis_kelamin')
                    ->required()
                    ->label('Jenis Kelamin')
                    ->options([
                        'L' => 'Laki-Laki',
                        'P' => 'Perempuan'
                    ])
                    ->hidden()
                    ->dehydrated(true),

                Forms\Components\Select::make('kabupaten')
                    ->required()
                    ->options([
                        'BALIKPAPAN' => 'BALIKPAPAN',
                        'BERAU' => 'BERAU',
                        'BONTANG' => 'BONTANG',
                        'KUTAI BARAT' => 'KUTAI BARAT',
                        'KUTAI KERTANEGARA' => 'KUTAI KERTANEGARA',
                        'KUTAI TIMUR' => 'KUTAI TIMUR',
                        'MAHAKAM ULU' => 'MAHAKAM ULU',
                        'PASER' => 'PASER',
                        'PENAJAM PASER UTARA' => 'PENAJAM PASER UTARA',
                        'SAMARINDA' => 'SAMARINDA',
                    ])
                    ->live(),

                Forms\Components\Select::make('kecamatan')
                    ->required()
                    ->options(fn (Forms\Get $get): array => match ($get('kabupaten')) {
                        'BALIKPAPAN' => [
                            'BALIKPAPAN KOTA' => 'BALIKPAPAN KOTA',
                            'BALIKPAPAN SELATAN' => 'BALIKPAPAN SELATAN',
                            'BALIKPAPAN TENGAH' => 'BALIKPAPAN TENGAH',
                            'BALIKPAPAN BARAT' => 'BALIKPAPAN BARAT',
                            'BALIKPAPAN TIMUR' => 'BALIKPAPAN TIMUR',
                            'BALIKPAPAN UTARA' => 'BALIKPAPAN UTARA',
                        ],
                        'BERAU' => [
                            'BATU PUTIH' => 'BATU PUTIH',
                            'BIATAN' => 'BIATAN',
                            'BIDUK-BIDUK' => 'BIDUK-BIDUK',
                            'GUNUNG TABUR' => 'GUNUNG TABUR',
                            'KELAY' => 'KELAY',
                            'MARATUA' => 'MARATUA',
                            'PULAU DERAWAN' => 'PULAU DERAWAN',
                            'SAMBALIUNG' => 'SAMBALIUNG',
                            'SEGAH' => 'SEGAH',
                            'TABALAR' => 'TABALAR',
                            'TALISAYAN' => 'TALISAYAN',
                            'TANJUNG REDEB' => 'TANJUNG REDEB',
                            'TELUK BAYUR' => 'TELUK BAYUR',
                        ],
                        'BONTANG' => [
                            'BONTANG BARAT' => 'BONTANG BARAT',
                            'BONTANG SELATAN' => 'BONTANG SELATAN',
                            'BONTANG UTARA' => 'BONTANG UTARA',
                        ],
                        'KUTAI BARAT' => [
                            'BARONG TONGKOK' => 'BARONG TONGKOK',
                            'BENTIAN BESAR' => 'BENTIAN BESAR',
                            'BONGAN' => 'BONGAN',
                            'DAMAI' => 'DAMAI',
                            'JEMPANG' => 'JEMPANG',
                            'LINGGANG BIGUNG' => 'LINGGANG BIGUNG',
                            'LONG IRAM' => 'LONG IRAM',
                            'MELAK' => 'MELAK',
                            'MOOK MANAAR BULATN' => 'MOOK MANAAR BULATN',
                            'MUARA LAWA' => 'MUARA LAWA',
                            'MUARA PAHU' => 'MUARA PAHU',
                            'NYUATAN' => 'NYUATAN',
                            'PENYINGGAHAN' => 'PENYINGGAHAN',
                            'SEKOLAQ DARAT' => 'SEKOLAQ DARAT',
                            'SILUQ NGURAI' => 'SILUQ NGURAI',
                            'TERING' => 'TERING',
                        ],
                        'KUTAI KERTANEGARA' => [
                            'ANGGANA' => 'ANGGANA',
                            'KEMBANG JANGGUT' => 'KEMBANG JANGGUT',
                            'KENOHAN' => 'KENOHAN',
                            'KOTA BANGUN' => 'KOTA BANGUN',
                            'LOA JANAN' => 'LOA JANAN',
                            'LOA KULU' => 'LOA KULU',
                            'MARANG KAYU' => 'MARANG KAYU',
                            'MUARA BADAK' => 'MUARA BADAK',
                            'MUARA JAWA' => 'MUARA JAWA',
                            'MUARA KAMAN' => 'MUARA KAMAN',
                            'MUARA MUNTAI' => 'MUARA MUNTAI',
                            'MUARA WIS' => 'MUARA WIS',
                            'SAMBOJA' => 'SAMBOJA',
                            'SANGA-SANGA' => 'SANGA-SANGA',
                            'SEBULU' => 'SEBULU',
                            'TABANG' => 'TABANG',
                            'TENGGARONG' => 'TENGGARONG',
                            'TENGGARONG SEBERANG' => 'TENGGARONG SEBERANG',
                        ],
                        'KUTAI TIMUR' => [
                            'BATU AMPAR' => 'BATU AMPAR',
                            'BENGALON' => 'BENGALON',
                            'BUSANG' => 'BUSANG',
                            'KALIORANG' => 'KALIORANG',
                            'KARANGAN' => 'KARANGAN',
                            'KAUBUN' => 'KAUBUN',
                            'KOMBENG' => 'KOMBENG',
                            'LONG MESANGAT' => 'LONG MESANGAT',
                            'MUARA ANCALONG' => 'MUARA ANCALONG',
                            'MUARA BENGKAL' => 'MUARA BENGKAL',
                            'MUARA WAHAU' => 'MUARA WAHAU',
                            'RANTAU PULUNG' => 'RANTAU PULUNG',
                            'SANDARAN' => 'SANDARAN',
                            'SANGATTA SELATAN' => 'SANGATTA SELATAN',
                            'SANGATTA UTARA' => 'SANGATTA UTARA',
                            'SANGKULIRANG' => 'SANGKULIRANG',
                            'TELEN' => 'TELEN',
                            'TELUK PANDAN' => 'TELUK PANDAN',
                        ],
                        'MAHAKAM ULU' => [
                            'LAHAM' => 'LAHAM',
                            'LONG APARI' => 'LONG APARI',
                            'LONG BAGUN' => 'LONG BAGUN',
                            'LONG HUBUNG' => 'LONG HUBUNG',
                            'LONG PAHANGAI' => 'LONG PAHANGAI',
                        ],
                        'PASER' => [
                            'BATU ENGAU' => 'BATU ENGAU',
                            'BATU SOPANG' => 'BATU SOPANG',
                            'KUARO' => 'KUARO',
                            'LONG IKIS' => 'LONG IKIS',
                            'LONG KALI' => 'LONG KALI',
                            'MUARA KOMAM' => 'MUARA KOMAM',
                            'MUARA SAMU' => 'MUARA SAMU',
                            'PASER BELENGKONG' => 'PASER BELENGKONG',
                            'TANAH GROGOT' => 'TANAH GROGOT',
                            'TANJUNG HARAPAN' => 'TANJUNG HARAPAN',
                        ],
                        'PENAJAM PASER UTARA' => [
                            'BABULU' => 'BABULU',
                            'PENAJAM' => 'PENAJAM',
                            'SEPAKU' => 'SEPAKU',
                            'WARU' => 'WARU',
                        ],
                        'SAMARINDA' => [
                            'LOA JANAN ILIR' => 'LOA JANAN ILIR',
                            'PALARAN' => 'PALARAN',
                            'SAMARINDA ILIR' => 'SAMARINDA ILIR',
                            'SAMARINDA KOTA' => 'SAMARINDA KOTA',
                            'SAMARINDA SEBERANG' => 'SAMARINDA SEBERANG',
                            'SAMARINDA ULU' => 'SAMARINDA ULU',
                            'SAMARINDA UTARA' => 'SAMARINDA UTARA',
                            'SAMBUTAN' => 'SAMBUTAN',
                            'SUNGAI KUNJANG' => 'SUNGAI KUNJANG',
                            'SUNGAI PINANG' => 'SUNGAI PINANG',
                        ],
                        default => [],
                    })
                    ->live(),

                Forms\Components\Select::make('kelurahan')
                    ->required()
                    ->options(function (Forms\Get $get): array {
                        $category = $get('kabupaten');
                        $subCategory = $get('kecamatan');

                        return match ([$category, $subCategory]) {
                            ['BALIKPAPAN', 'BALIKPAPAN KOTA'] => [
                                'DAMAI' => 'DAMAI',
                                'KLANDASAN ILIR' => 'KLANDASAN ILIR',
                                'KLANDASAN ULU' => 'KLANDASAN ULU',
                                'PRAPATAN' => 'PRAPATAN',
                                'TELAGA SARI' => 'TELAGA SARI',
                            ],
                            ['BALIKPAPAN', 'BALIKPAPAN UTARA'] => [
                                'BATU AMPAR' => 'BATU AMPAR',
                                'GRAHA INDAH' => 'GRAHA INDAH',
                                'GUNUNGSAMARINDA' => 'GUNUNGSAMARINDA',
                                'GUNUNGSAMARINDA BARU' => 'GUNUNGSAMARINDA BARU',
                                'KARANG JOANG' => 'KARANG JOANG',
                                'MUARARAPAK' => 'MUARARAPAK',
                            ],
                            ['BALIKPAPAN', 'BALIKPAPAN TIMUR'] => [
                                'LAMARU' => 'LAMARU',
                                'MANGGAR' => 'MANGGAR',
                                'MANGGAR BARU' => 'MANGGAR BARU',
                                'TERITIP' => 'TERITIP',
                            ],
                            ['BALIKPAPAN', 'BALIKPAPAN BARAT'] => [
                                'BARU ILIR' => 'BARU ILIR',
                                'BARU TENGAH' => 'BARU TENGAH',
                                'BARU ULU' => 'BARU ULU',
                                'KARIANGAU' => 'KARIANGAU',
                                'MARGASARI' => 'MARGASARI',
                                'MARGO MULYO' => 'MARGO MULYO',
                            ],
                            ['BALIKPAPAN', 'BALIKPAPAN SELATAN'] => [
                                'DAMAI BAHAGIA' => 'DAMAI BAHAGIA',
                                'DAMAI BARU' => 'DAMAI BARU',
                                'GUNUNGBAHAGIA' => 'GUNUNGBAHAGIA',
                                'SEPINGGAN' => 'SEPINGGAN',
                                'SEPINGGAN BARU' => 'SEPINGGAN BARU',
                                'SEPINGGAN RAYA' => 'SEPINGGAN RAYA',
                                'SUNGAINANGKA' => 'SUNGAINANGKA',
                            ],
                            ['BALIKPAPAN', 'BALIKPAPAN TENGAH'] => [
                                'GUNUNGSARI ILIR' => 'GUNUNGSARI ILIR',
                                'GUNUNGSARI ULU' => 'GUNUNGSARI ULU',
                                'KARANG JATI' => 'KARANG JATI',
                                'KARANG REJO' => 'KARANG REJO',
                                'MEKAR SARI' => 'MEKAR SARI',
                                'SUMBER REJO' => 'SUMBER REJO',
                            ],
                            ['BERAU', 'BATU PUTIH'] => [
                                'BATU PUTIH' => 'BATU PUTIH',
                                'TEMBUDAN' => 'TEMBUDAN',
                                'SUMBER AGUNG' => 'SUMBER AGUNG',
                                'BALIKUKUP' => 'BALIKUKUP',
                                'LOBANG KELATAK' => 'LOBANG KELATAK',
                                'AMPEN MEDANG' => 'AMPEN MEDANG',
                                'KAYU INDAH' => 'KAYU INDAH',
                            ],
                            ['BERAU', 'BIATAN'] => [
                                'BIATAN LEMPAKE' => 'BIATAN LEMPAKE',
                                'BIATAN ILIR' => 'BIATAN ILIR',
                                'BIATAN BAPINANG' => 'BIATAN BAPINANG',
                                'BIATAN BARU' => 'BIATAN BARU',
                                'KARANGAN' => 'KARANGAN',
                                'MANUNGGAL JAYA' => 'MANUNGGAL JAYA',
                                'BUKIT MAKMUR JAYA' => 'BUKIT MAKMUR JAYA',
                                'BIATAN ULU' => 'BIATAN ULU',
                            ],
                            ['BERAU', 'BIDUK-BIDUK'] => [
                                'BIDUK-BIDUK' => 'BIDUK-BIDUK',
                                'TELUK SULAIMAN' => 'TELUK SULAIMAN',
                                'TANJUNG PREPAT' => 'TANJUNG PREPAT',
                                'GIRING-GIRING' => 'GIRING-GIRING',
                                'TELUK SUMBANG' => 'TELUK SUMBANG',
                                'PANTAI HARAPAN' => 'PANTAI HARAPAN',
                            ],
                            ['BERAU', 'GUNUNG TABUR'] => [
                                'TASUK' => 'TASUK',
                                'MALUANG' => 'MALUANG',
                                'MERANCANG ULU' => 'MERANCANG ULU',
                                'SAMBAKUNGAN' => 'SAMBAKUNGAN',
                                'BATU-BATU' => 'BATU-BATU',
                                'MERANCANG ILIR' => 'MERANCANG ILIR',
                                'SAMBURAKAT' => 'SAMBURAKAT',
                                'BIRANG' => 'BIRANG',
                                'MELATI JAYA' => 'MELATI JAYA',
                                'PULAU BESING' => 'PULAU BESING',
                            ],
                            ['BERAU', 'KELAY'] => [
                                'MERAPUN' => 'MERAPUN',
                                'MERABU' => 'MERABU',
                                'SIDO BANGEN' => 'SIDO BANGEN',
                                'LONG BELIU' => 'LONG BELIU',
                                'MERASA' => 'MERASA',
                                'MUARA LESAN' => 'MUARA LESAN',
                                'LONG DUHUNG' => 'LONG DUHUNG',
                                'LESAN DAYAK' => 'LESAN DAYAK',
                                'LONG KELUH' => 'LONG KELUH',
                                'LONG PELAY' => 'LONG PELAY',
                                'PANAAN' => 'PANAAN',
                                'LONG LAMCIN' => 'LONG LAMCIN',
                                'LONG SULUI' => 'LONG SULUI',
                            ],
                            ['BERAU', 'MARATUA'] => [
                                'TELUK HARAPAN' => 'TELUK HARAPAN',
                                'BOHE SILIAN' => 'BOHE SILIAN',
                                'PAYUNG-PAYUNG' => 'PAYUNG-PAYUNG',
                                'TELUK ALULU' => 'TELUK ALULU',
                            ],
                            ['BERAU', 'PULAU DERAWAN'] => [
                                'TANJUNG BATU' => 'TANJUNG BATU',
                                'PULAU DERAWAN' => 'PULAU DERAWAN',
                                'KASAI' => 'KASAI',
                                'TELUK SEMANTING' => 'TELUK SEMANTING',
                                'PEGAT BATUMBUK' => 'PEGAT BATUMBUK',
                            ],
                            ['BERAU', 'SAMBALIUNG'] => [
                                'GURIMBANG' => 'GURIMBANG',
                                'SUKAN TENGAH' => 'SUKAN TENGAH',
                                'SEI BEBANIR BANGUN' => 'SEI BEBANIR BANGUN',
                                'PEGAT BUKUR' => 'PEGAT BUKUR',
                                'TANJUNG PERANGAT' => 'TANJUNG PERANGAT',
                                'SUARAN' => 'SUARAN',
                                'PILANJAU' => 'PILANJAU',
                                'PESAYAN' => 'PESAYAN',
                                'RANTAU PANJANG' => 'RANTAU PANJANG',
                                'BENA BARU' => 'BENA BARU',
                                'INARAN' => 'INARAN',
                                'TUMBIT DAYAK' => 'TUMBIT DAYAK',
                                'LONG LANUK' => 'LONG LANUK',
                                'SAMBALIUNG' => 'SAMBALIUNG',
                            ],
                            ['BERAU', 'SEGAH'] => [
                                'HARAPAN JAYA' => 'HARAPAN JAYA',
                                'TEPIAN BUAH' => 'TEPIAN BUAH',
                                'GUNUNG SARI' => 'GUNUNG SARI',
                                'LONG AYAN' => 'LONG AYAN',
                                'BUKIT MAKMUR' => 'BUKIT MAKMUR',
                                'LONG LA\'AI' => 'LONG LA\'AI',
                                'PANDAN SARI' => 'PANDAN SARI',
                                'SIDUUNG INDAH' => 'SIDUUNG INDAH',
                                'PUNAN MALINAU' => 'PUNAN MALINAU',
                                'PUNAN MAHKAM' => 'PUNAN MAHKAM',
                                'PUNAN SEGAH' => 'PUNAN SEGAH',
                                'LONG AYAP' => 'LONG AYAP',
                                'BATU RAJANG' => 'BATU RAJANG',
                            ],
                            ['BERAU', 'TABALAR'] => [
                                'TUBAAN' => 'TUBAAN',
                                'TABALAR MUARA' => 'TABALAR MUARA',
                                'HARAPAN MAJU' => 'HARAPAN MAJU',
                                'BUYUNG-BUYUNG' => 'BUYUNG-BUYUNG',
                                'SEMURUT' => 'SEMURUT',
                                'TABALAR ULU' => 'TABALAR ULU',
                            ],
                            ['BERAU', 'TALISAYAN'] => [
                                'TALISAYAN' => 'TALISAYAN',
                                'SUKA MURYA' => 'SUKA MURYA',
                                'DUMARING' => 'DUMARING',
                                'BUMI JAYA' => 'BUMI JAYA',
                                'CAMPUR SARI' => 'CAMPUR SARI',
                                'EKA SAPTA' => 'EKA SAPTA',
                                'TUNGGAL BUMI' => 'TUNGGAL BUMI',
                                'PURNA SARI JAYA' => 'PURNA SARI JAYA',
                                'CAPUAK' => 'CAPUAK',
                                'SUMBER MULYA' => 'SUMBER MULYA',
                            ],
                            ['BERAU', 'TANJUNG REDEB'] => [
                                'BUGIS' => 'BUGIS',
                                'GAYAM' => 'GAYAM',
                                'GUNUNG PANJANG' => 'GUNUNG PANJANG',
                                'KARANG AMBUN' => 'KARANG AMBUN',
                                'SUNGAI BEDUNGUN' => 'SUNGAI BEDUNGUN',
                                'TANJUNG REDEB' => 'TANJUNG REDEB',
                            ],
                            ['BERAU', 'TELUK BAYUR'] => [
                                'LABANAN MAKMUR' => 'LABANAN MAKMUR',
                                'LABANAN JAYA' => 'LABANAN JAYA',
                                'LABANAN MAKARTI' => 'LABANAN MAKARTI',
                                'TUMBIT MELAYU' => 'TUMBIT MELAYU',
                                'RINDING' => 'RINDING',
                            ],
                            ['BONTANG', 'BONTANG BARAT'] => [
                                'BELIMBING' => 'BELIMBING',
                                'KANAAN' => 'KANAAN',
                                'GUNUNG TELIHAN' => 'GUNUNG TELIHAN',
                            ],
                            ['BONTANG', 'BONTANG SELATAN'] => [
                                'BERBAS PANTAI' => 'BERBAS PANTAI',
                                'BERBAS TENGAH' => 'BERBAS TENGAH',
                                'BONTANG LESTARI' => 'BONTANG LESTARI',
                                'SATIMPO' => 'SATIMPO',
                                'TANJUNG LAUT' => 'TANJUNG LAUT',
                                'TANJUNG LAUT INDAH' => 'TANJUNG LAUT INDAH',
                            ],
                            ['BONTANG', 'BONTANG UTARA'] => [
                                'API-API' => 'API-API',
                                'BONTANG BARU' => 'BONTANG BARU',
                                'BONTANG KUALA' => 'BONTANG KUALA',
                                'GUNTUNG' => 'GUNTUNG',
                                'GUNUNG ELAI' => 'GUNUNG ELAI',
                                'LOK TUAN' => 'LOK TUAN',
                            ],
                            ['KUTAI BARAT', 'BARONG TONGKOK'] => [
                                'SUMBER SARI' => 'SUMBER SARI',
                                'JUAQ ASA' => 'JUAQ ASA',
                                'REJO BASUKI' => 'REJO BASUKI',
                                'NGENYAN ASA' => 'NGENYAN ASA',
                                'SENDAWAR' => 'SENDAWAR',
                                'GEMUHAN ASA' => 'GEMUHAN ASA',
                                'GELEO ASA' => 'GELEO ASA',
                                'PEPES ASA' => 'PEPES ASA',
                                'JUHAN ASA' => 'JUHAN ASA',
                                'GELEO BARU' => 'GELEO BARU',
                                'MUARA ASA' => 'MUARA ASA',
                                'OMBAU ASA' => 'OMBAU ASA',
                                'MENCIMAI' => 'MENCIMAI',
                                'BALOK ASA' => 'BALOK ASA',
                                'ASA' => 'ASA',
                                'PEPAS EHENG' => 'PEPAS EHENG',
                                'BELEMPUNG ULAQ' => 'BELEMPUNG ULAQ',
                                'ENGKUNI PASEK' => 'ENGKUNI PASEK',
                                'ONGKO ASA' => 'ONGKO ASA',
                            ],
                            ['KUTAI BARAT', 'BENTIAN BESAR'] => [
                                'DILANG PUTI' => 'DILANG PUTI',
                                'TUKUQ' => 'TUKUQ',
                                'SUAKONG' => 'SUAKONG',
                                'PENARUNG' => 'PENARUNG',
                                'SAMBUNG' => 'SAMBUNG',
                                'TENDE' => 'TENDE',
                                'JELMU SIBAK' => 'JELMU SIBAK',
                                'RANDA EMPAS' => 'RANDA EMPAS',
                                'ANAN JAYA' => 'ANAN JAYA',
                            ],
                            ['KUTAI BARAT', 'BONGAN'] => [
                                'PENAWAI' => 'PENAWAI',
                                'MUARA KEDANG' => 'MUARA KEDANG',
                                'JAMBUK MAKMUR' => 'JAMBUK MAKMUR',
                                'MUARA GUSIK' => 'MUARA GUSIK',
                                'JAMBUK' => 'JAMBUK',
                                'TANJUNG SARI' => 'TANJUNG SARI',
                                'BUKIT HARAPAN' => 'BUKIT HARAPAN',
                                'RESAK' => 'RESAK',
                                'SIRAM JAYA' => 'SIRAM JAYA',
                                'SIRAM MAKMUR' => 'SIRAM MAKMUR',
                                'TANJUNG SOKE' => 'TANJUNG SOKE',
                                'PERENG TALIQ' => 'PERENG TALIQ',
                                'MUARA SIRAM' => 'MUARA SIRAM',
                                'LEMPER' => 'LEMPER',
                                'DERAYA' => 'DERAYA',
                                'GERUNGUNG' => 'GERUNGUNG',
                            ],
                            ['KUTAI BARAT', 'DAMAI'] => [
                                'JENGANG DANUM' => 'JENGANG DANUM',
                                'KEAY' => 'KEAY',
                                'DAMAI KOTA' => 'DAMAI KOTA',
                                'MENDIKA' => 'MENDIKA',
                                'MUARA BOMBOY' => 'MUARA BOMBOY',
                                'BENUNG' => 'BENUNG',
                                'TAPULANG' => 'TAPULANG',
                                'DAMAI SEBERANG' => 'DAMAI SEBERANG',
                                'SEMPATN' => 'SEMPATN',
                                'MANTAR' => 'MANTAR',
                                'MUARA NYAHING' => 'MUARA NYAHING',
                                'MUARA NILIQ' => 'MUARA NILIQ',
                                'MUARA TOKONG' => 'MUARA TOKONG',
                                'BESIQ' => 'BESIQ',
                                'LUMPAT DAHUQ' => 'LUMPAT DAHUQ',
                                'KELIAN' => 'KELIAN',
                                'BERMAI' => 'BERMAI',
                            ],
                            ['KUTAI BARAT', 'JEMPANG'] => [
                                'TANJUNG ISUY' => 'TANJUNG ISUY',
                                'MUARA TAE' => 'MUARA TAE',
                                'PULAU LANTING' => 'PULAU LANTING',
                                'TANJUNG JAN' => 'TANJUNG JAN',
                                'BEKOKONG MAKMUR' => 'BEKOKONG MAKMUR',
                                'MANCONG' => 'MANCONG',
                                'MUARA NAYAN' => 'MUARA NAYAN',
                                'TANJUNG JONE' => 'TANJUNG JONE',
                                'MUARA OHONG' => 'MUARA OHONG',
                                'PENTAT' => 'PENTAT',
                                'LEMBONAH' => 'LEMBONAH',
                                'PERIGIQ' => 'PERIGIQ',
                            ],
                            ['KUTAI BARAT', 'LINGGANG BIGUNG'] => [
                                'LINGGANG BIGUNG' => 'LINGGANG BIGUNG',
                                'LINGGANG MELAPEH' => 'LINGGANG MELAPEH',
                                'LINGGANG MAPAN' => 'LINGGANG MAPAN',
                                'LINGGANG BANGUNSARI' => 'LINGGANG BANGUNSARI',
                                'LINGGANG PURWODADI' => 'LINGGANG PURWODADI',
                                'LINGGANG MENCELEW' => 'LINGGANG MENCELEW',
                                'LINGGANG KEBUT' => 'LINGGANG KEBUT',
                                'LINGGANG MELAPEH BARU' => 'LINGGANG MELAPEH BARU',
                                'LINGGANG BIGUNG BARU' => 'LINGGANG BIGUNG BARU',
                                'LINGGANG AMER' => 'LINGGANG AMER',
                                'LINGGANG TUTUNG' => 'LINGGANG TUTUNG',
                            ],
                            ['KUTAI BARAT', 'LONG IRAM'] => [
                                'LONG IRAM KOTA' => 'LONG IRAM KOTA',
                                'SUKOMULYO' => 'SUKOMULYO',
                                'LONG IRAM SEBERANG' => 'LONG IRAM SEBERANG',
                                'LONG IRAM BAYAN' => 'LONG IRAM BAYAN',
                                'ANAH' => 'ANAH',
                                'LONG IRAM ILIR' => 'LONG IRAM ILIR',
                                'KELIWAI' => 'KELIWAI',
                                'LINGGANG MUARA LEBAN' => 'LINGGANG MUARA LEBAN',
                                'KELIAN LUAR' => 'KELIAN LUAR',
                                'UJOH HALANG' => 'UJOH HALANG',
                                'LONG DALIQ' => 'LONG DALIQ',
                            ],
                            ['KUTAI BARAT', 'MELAK'] => [
                                'EMPAKUQ' => 'EMPAKUQ',
                                'MUARA BENANGAQ' => 'MUARA BENANGAQ',
                                'MUARA BUNYUT' => 'MUARA BUNYUT',
                                'EMPAS' => 'EMPAS',
                                'MELAK ILIR' => 'MELAK ILIR',
                                'MELAK ULU' => 'MELAK ULU',
                            ],
                            ['KUTAI BARAT', 'MOOK MANAAR BULATN'] => [
                                'KARANGAN' => 'KARANGAN',
                                'GUNUNG RAMPAH' => 'GUNUNG RAMPAH',
                                'KELUMPANG' => 'KELUMPANG',
                                'SAKAQ TADA' => 'SAKAQ TADA',
                                'GEMURUH' => 'GEMURUH',
                                'LINGGANG MARIMUN' => 'LINGGANG MARIMUN',
                                'JENGAN' => 'JENGAN',
                                'MUARA KALAQ' => 'MUARA KALAQ',
                                'SAKAQ LOTOQ' => 'SAKAQ LOTOQ',
                                'GADUR' => 'GADUR',
                                'ABIT' => 'ABIT',
                                'MUARA JAWAQ' => 'MUARA JAWAQ',
                                'LINGGANG MUARA BATUQ' => 'LINGGANG MUARA BATUQ',
                                'TONDOH' => 'TONDOH',
                                'REMBAYAN' => 'REMBAYAN',
                                'MERAYAQ' => 'MERAYAQ',
                            ],
                            ['KUTAI BARAT', 'MUARA LAWA'] => [
                                'MUARA LAWA' => 'MUARA LAWA',
                                'CEMPEDES' => 'CEMPEDES',
                                'LAMBING' => 'LAMBING',
                                'PAYANG' => 'PAYANG',
                                'DINGIN' => 'DINGIN',
                                'BENGGERIS' => 'BENGGERIS',
                                'LOTAQ' => 'LOTAQ',
                                'MUARA BEGAI' => 'MUARA BEGAI',
                            ],
                            ['KUTAI BARAT', 'MUARA PAHU'] => [
                                'TANJUNG LAONG' => 'TANJUNG LAONG',
                                'MUARA BAROH' => 'MUARA BAROH',
                                'TELUK TEMPUDAU' => 'TELUK TEMPUDAU',
                                'TEPIAN ULAQ' => 'TEPIAN ULAQ',
                                'SEBELANG' => 'SEBELANG',
                                'TANJUNG PAGAR' => 'TANJUNG PAGAR',
                                'JERANG MELAYU' => 'JERANG MELAYU',
                                'MUARA BELOAN' => 'MUARA BELOAN',
                                'GUNUNG BAYAN' => 'GUNUNG BAYAN',
                                'DASAQ' => 'DASAQ',
                                'MENDUNG' => 'MENDUNG',
                                'JERANG DAYAK' => 'JERANG DAYAK',
                            ],
                            ['KUTAI BARAT', 'NYUATAN'] => [
                                'TERAJUK' => 'TERAJUK',
                                'DEMPAR' => 'DEMPAR',
                                'SEMBUAN' => 'SEMBUAN',
                                'TEMULA' => 'TEMULA',
                                'MU\'UT' => 'MU\'UT',
                                'AWAI' => 'AWAI',
                                'INTU LINGAU' => 'INTU LINGAU',
                                'JONTAI' => 'JONTAI',
                                'LAKAN BILEM' => 'LAKAN BILEM',
                                'SENTALAR' => 'SENTALAR',
                            ],
                            ['KUTAI BARAT', 'PENYINGGAHAN'] => [
                                'PENYINGGAHAN ULU' => 'PENYINGGAHAN ULU',
                                'LOA DERAS' => 'LOA DERAS',
                                'PENYINGGAHAN ILIR' => 'PENYINGGAHAN ILIR',
                                'TANJUNG HAUR' => 'TANJUNG HAUR',
                                'MINTA' => 'MINTA',
                                'BAKUNG' => 'BAKUNG',
                            ],
                            ['KUTAI BARAT', 'SEKOLAQ DARAT'] => [
                                'SEKOLAQ DARAT' => 'SEKOLAQ DARAT',
                                'SUMBER BANGUN' => 'SUMBER BANGUN',
                                'SEKOLAQ JOLEQ' => 'SEKOLAQ JOLEQ',
                                'SUMBER REJO' => 'SUMBER REJO',
                                'SRIMULYO' => 'SRIMULYO',
                                'SEKOLAQ ODAY' => 'SEKOLAQ ODAY',
                                'LELENG' => 'LELENG',
                                'SEKOLAQ MULIAQ' => 'SEKOLAQ MULIAQ',
                            ],
                            ['KUTAI BARAT', 'SILUQ NGURAI'] => [
                                'MUHUR' => 'MUHUR',
                                'SANG-SANG' => 'SANG-SANG',
                                'MUARA KELAWIT' => 'MUARA KELAWIT',
                                'TEBISAQ' => 'TEBISAQ',
                                'KALIQ' => 'KALIQ',
                                'TANAH MEA' => 'TANAH MEA',
                                'LENDIAN LIANG NAYUQ' => 'LENDIAN LIANG NAYUQ',
                                'BENTAS' => 'BENTAS',
                                'RIKONG' => 'RIKONG',
                                'MUARA PONAQ' => 'MUARA PONAQ',
                                'KENDISIQ' => 'KENDISIQ',
                                'PENAWANG' => 'PENAWANG',
                                'KIAQ' => 'KIAQ',
                                'KENYANYAN' => 'KENYANYAN',
                                'TENDIQ' => 'TENDIQ',
                                'BETUNG' => 'BETUNG',
                            ],
                            ['KUTAI BARAT', 'TERING'] => [
                                'TERING SEBERANG' => 'TERING SEBERANG',
                                'PURWOREJO' => 'PURWOREJO',
                                'MUYUB AKET' => 'MUYUB AKET',
                                'MUARA MUJAN' => 'MUARA MUJAN',
                                'TERING LAMA ULU' => 'TERING LAMA ULU',
                                'BANJAREJO' => 'BANJAREJO',
                                'TERING LAMA' => 'TERING LAMA',
                                'KELUBAQ' => 'KELUBAQ',
                                'TERING BARU' => 'TERING BARU',
                                'KELIAN DALAM' => 'KELIAN DALAM',
                                'JELEMUQ' => 'JELEMUQ',
                                'GABUNG BARU' => 'GABUNG BARU',
                                'MUYUB ULU' => 'MUYUB ULU',
                                'TUKUL' => 'TUKUL',
                                'MUYUB ILIR' => 'MUYUB ILIR',
                            ],
                            ['KUTAI KERTANEGARA', 'ANGGANA'] => [
                                'SUNGAI MERIAM' => 'SUNGAI MERIAM',
                                'ANGGANA' => 'ANGGANA',
                                'SIDOMULYO' => 'SIDOMULYO',
                                'KUTAI LAMA' => 'KUTAI LAMA',
                                'SEPATIN' => 'SEPATIN',
                                'MUARA PANTUAN' => 'MUARA PANTUAN',
                                'HANDIL TERUSAN' => 'HANDIL TERUSAN',
                                'TANI BARU' => 'TANI BARU',
                                'SUNGAI TEMPURUNG' => 'SUNGAI TEMPURUNG',
                            ],
                            ['KUTAI KERTANEGARA', 'KEMBANG JANGGUT'] => [
                                'KEMBANG JANGGUT' => 'KEMBANG JANGGUT',
                                'HAMBAU' => 'HAMBAU',
                                'LONG BELEH MODANG' => 'LONG BELEH MODANG',
                                'GENTING TANAH' => 'GENTING TANAH',
                                'PERDANA' => 'PERDANA',
                                'MUAI' => 'MUAI',
                                'LONG BELEH HALOQ' => 'LONG BELEH HALOQ',
                                'LOA SAKOH' => 'LOA SAKOH',
                                'PULAU PINANG' => 'PULAU PINANG',
                                'KELEKAT' => 'KELEKAT',
                                'BUKIT LAYANG' => 'BUKIT LAYANG',
                            ],
                            ['KUTAI KERTANEGARA', 'KENOHAN'] => [
                                'TUANA TUHA' => 'TUANA TUHA',
                                'LAMIN TELIHAN' => 'LAMIN TELIHAN',
                                'LAMIN PULUT' => 'LAMIN PULUT',
                                'TELUK BINGKAI' => 'TELUK BINGKAI',
                                'SEMAYANG' => 'SEMAYANG',
                                'TUBUHAN' => 'TUBUHAN',
                                'TELUK MUDA' => 'TELUK MUDA',
                                'KAHALA' => 'KAHALA',
                                'KAHALA ILIR' => 'KAHALA ILIR',
                            ],
                            ['KUTAI KERTANEGARA', 'KOTA BANGUN'] => [
                                'KOTA BANGUN ULU' => 'KOTA BANGUN ULU',
                                'KOTA BANGUN III' => 'KOTA BANGUN III',
                                'KEDANG IPIL' => 'KEDANG IPIL',
                                'PELA' => 'PELA',
                                'LIANG' => 'LIANG',
                                'KOTA BANGUN II' => 'KOTA BANGUN II',
                                'LOLENG' => 'LOLENG',
                                'KOTA BANGUN ILIR' => 'KOTA BANGUN ILIR',
                                'KOTA BANGUN I' => 'KOTA BANGUN I',
                                'KEDANG MURUNG' => 'KEDANG MURUNG',
                                'SARI NADI' => 'SARI NADI',
                                'SUMBER SARI' => 'SUMBER SARI',
                                'KOTA BANGUN SEBERANG' => 'KOTA BANGUN SEBERANG',
                                'LIANG ULU' => 'LIANG ULU',
                                'SUKA BUMI' => 'SUKA BUMI',
                                'SEBELIMBINGAN' => 'SEBELIMBINGAN',
                                'SANGKULIMAN' => 'SANGKULIMAN',
                                'MUHURAN' => 'MUHURAN',
                                'SEDULANG' => 'SEDULANG',
                                'WONOSARI' => 'WONOSARI',
                                'BENUA BARU' => 'BENUA BARU',
                            ],
                            ['KUTAI KERTANEGARA', 'LOA JANAN'] => [
                                'LOA DURI ILIR' => 'LOA DURI ILIR',
                                'LOA DURI ULU' => 'LOA DURI ULU',
                                'BATUAH' => 'BATUAH',
                                'PURWAJAYA' => 'PURWAJAYA',
                                'BAKUNGAN' => 'BAKUNGAN',
                                'TANI BHAKTI' => 'TANI BHAKTI',
                                'LOA JANAN ULU' => 'LOA JANAN ULU',
                                'TANI HARAPAN' => 'TANI HARAPAN',
                            ],
                            ['KUTAI KERTANEGARA', 'LOA KULU'] => [
                                'REMPANGA' => 'REMPANGA',
                                'LOA KULU KOTA' => 'LOA KULU KOTA',
                                'LOH SUMBER' => 'LOH SUMBER',
                                'PONORAGAN' => 'PONORAGAN',
                                'SEPAKAT' => 'SEPAKAT',
                                'SUMBER SARI' => 'SUMBER SARI',
                                'JONGKANG' => 'JONGKANG',
                                'LUNG ANAI' => 'LUNG ANAI',
                                'MARGA RAHAYU' => 'MARGA RAHAYU',
                                'JONGGON JAYA' => 'JONGGON JAYA',
                                'JEMBAYAN' => 'JEMBAYAN',
                                'JEMBAYAN DALAM' => 'JEMBAYAN DALAM',
                                'SUNGAI PAYANG' => 'SUNGAI PAYANG',
                                'JEMBAYAN TENGAH' => 'JEMBAYAN TENGAH',
                                'JONGGON DESA' => 'JONGGON DESA',
                            ],
                            ['KUTAI KERTANEGARA', 'MARANG KAYU'] => [
                                'SEBUNTAL' => 'SEBUNTAL',
                                'PRANGAT SELATAN' => 'PRANGAT SELATAN',
                                'SANTAN ULU' => 'SANTAN ULU',
                                'SEMANGKOK' => 'SEMANGKOK',
                                'BUNGA PUTIH' => 'BUNGA PUTIH',
                                'MAKARTI' => 'MAKARTI',
                                'PRANGAT BARU' => 'PRANGAT BARU',
                                'KERSIK' => 'KERSIK',
                                'SAMBERA BARU' => 'SAMBERA BARU',
                                'SANTAN TENGAH' => 'SANTAN TENGAH',
                                'SANTAN ILIR' => 'SANTAN ILIR',
                            ],
                            ['KUTAI KERTANEGARA', 'MUARA BADAK'] => [
                                'BADAK BARU' => 'BADAK BARU',
                                'MUARA BADAK ILIR' => 'MUARA BADAK ILIR',
                                'GAS ALAM BADAK I' => 'GAS ALAM BADAK I',
                                'MUARA BADAK ULU' => 'MUARA BADAK ULU',
                                'TANAH DATAR' => 'TANAH DATAR',
                                'TANJUNG LIMAU' => 'TANJUNG LIMAU',
                                'BATU-BATU' => 'BATU-BATU',
                                'SALO PALAI' => 'SALO PALAI',
                                'SUKA DAMAI' => 'SUKA DAMAI',
                                'SALO CELLA' => 'SALO CELLA',
                                'SALIKI' => 'SALIKI',
                                'SUNGAI BAWANG' => 'SUNGAI BAWANG',
                                'BADAK MEKAR' => 'BADAK MEKAR',
                            ],
                            ['KUTAI KERTANEGARA', 'MUARA JAWA'] => [
                                'DONDANG' => 'DONDANG',
                                'MUARA JAWA ILIR' => 'MUARA JAWA ILIR',
                                'MUARA JAWA PESISIR' => 'MUARA JAWA PESISIR',
                                'MUARA JAWA TENGAH' => 'MUARA JAWA TENGAH',
                                'MUARA JAWA ULU' => 'MUARA JAWA ULU',
                                'MUARA KEMBANG' => 'MUARA KEMBANG',
                                'TAMA POLE' => 'TAMA POLE',
                                'TELUK DALAM' => 'TELUK DALAM',
                            ],
                            ['KUTAI KERTANEGARA', 'MUARA KAMAN'] => [
                                'PANCA JAYA' => 'PANCA JAYA',
                                'BUNGA JADI' => 'BUNGA JADI',
                                'BENUA PUHUN' => 'BENUA PUHUN',
                                'MUARA KAMAN ULU' => 'MUARA KAMAN ULU',
                                'SIDOMUKTI' => 'SIDOMUKTI',
                                'MUARA KAMAN ILIR' => 'MUARA KAMAN ILIR',
                                'MUARA SIRAN' => 'MUARA SIRAN',
                                'PUAN CEPAK' => 'PUAN CEPAK',
                                'TERATAK' => 'TERATAK',
                                'RANTAU HEMPANG' => 'RANTAU HEMPANG',
                                'LEBAHO ULAQ' => 'LEBAHO ULAQ',
                                'SABINTULUNG' => 'SABINTULUNG',
                                'BUKIT JERING' => 'BUKIT JERING',
                                'CIPARI MAKMUR' => 'CIPARI MAKMUR',
                                'SEDULANG' => 'SEDULANG',
                                'MENAMANG KIRI' => 'MENAMANG KIRI',
                                'MENAMANG KANAN' => 'MENAMANG KANAN',
                                'TUNJUNGAN' => 'TUNJUNGAN',
                                'LIANG BUAYA' => 'LIANG BUAYA',
                                'KUPANG BARU' => 'KUPANG BARU',
                            ],
                            ['KUTAI KERTANEGARA', 'MUARA MUNTAI'] => [
                                'PERIAN' => 'PERIAN',
                                'MUARA MUNTAI ILIR' => 'MUARA MUNTAI ILIR',
                                'MUARA MUNTAI ULU' => 'MUARA MUNTAI ULU',
                                'PULAU HARAPAN' => 'PULAU HARAPAN',
                                'KAYU BATU' => 'KAYU BATU',
                                'MUARA LEKA' => 'MUARA LEKA',
                                'JANTUR BARU' => 'JANTUR BARU',
                                'BATUQ' => 'BATUQ',
                                'JANTUR' => 'JANTUR',
                                'JANTUR SELATAN' => 'JANTUR SELATAN',
                                'REBAQ RINDING' => 'REBAQ RINDING',
                                'MUARA ALOH' => 'MUARA ALOH',
                                'TANJUNG BATUQ HARAPAN' => 'TANJUNG BATUQ HARAPAN',
                            ],
                            ['KUTAI KERTANEGARA', 'MUARA WIS'] => [
                                'LEBAK CILONG' => 'LEBAK CILONG',
                                'MUARA WIS' => 'MUARA WIS',
                                'LEBAK MANTAN' => 'LEBAK MANTAN',
                                'MUARA ENGGELAM' => 'MUARA ENGGELAM',
                                'MELINTANG' => 'MELINTANG',
                                'SEBEMBAN' => 'SEBEMBAN',
                                'ENGGELAM' => 'ENGGELAM',
                            ],
                            ['KUTAI KERTANEGARA', 'SAMBOJA'] => [
                                'TANI BHAKTI' => 'TANI BHAKTI',
                                'BUKIT RAYA' => 'BUKIT RAYA',
                                'KARYA JAYA' => 'KARYA JAYA',
                                'BERINGIN AGUNG' => 'BERINGIN AGUNG',
                                'AMBARAWANG DARAT' => 'AMBARAWANG DARAT',
                                'AMBARAWANG LAUT' => 'AMBARAWANG LAUT',
                                'ARGOSARI' => 'ARGOSARI',
                                'BUKIT MERDEKA' => 'BUKIT MERDEKA',
                                'HANDIL BARU' => 'HANDIL BARU',
                                'HANDIL BARU DARAT' => 'HANDIL BARU DARAT',
                                'KAMPUNG LAMA' => 'KAMPUNG LAMA',
                                'KARYA MERDEKA' => 'KARYA MERDEKA',
                                'MARGOMULYO' => 'MARGOMULYO',
                                'MUARA SEMBILANG' => 'MUARA SEMBILANG',
                                'SALOK API DARAT' => 'SALOK API DARAT',
                                'SALOK API LAUT' => 'SALOK API LAUT',
                                'SAMBOJA KUALA' => 'SAMBOJA KUALA',
                                'SANIPAH' => 'SANIPAH',
                                'SEI MERDEKA' => 'SEI MERDEKA',
                                'SUNGAI SELUANG' => 'SUNGAI SELUANG',
                                'WONOTIRTO' => 'WONOTIRTO',
                                'TANJUNG HARAPAN' => 'TANJUNG HARAPAN',
                                'TELUK PEMEDAS' => 'TELUK PEMEDAS',
                            ],
                            ['KUTAI KERTANEGARA', 'SANGA-SANGA'] => [
                                'JAWA' => 'JAWA',
                                'PENDINGIN' => 'PENDINGIN',
                                'SANGA-SANGA DALAM' => 'SANGA-SANGA DALAM',
                                'SANGA-SANGA MUARA' => 'SANGA-SANGA MUARA',
                                'SARI JAYA' => 'SARI JAYA',
                            ],
                            ['KUTAI KERTANEGARA', 'SEBULU'] => [
                                'SUMBER SARI' => 'SUMBER SARI',
                                'MANUNGGAL DAYA' => 'MANUNGGAL DAYA',
                                'SEBULU ULU' => 'SEBULU ULU',
                                'SEBULU ILIR' => 'SEBULU ILIR',
                                'SEBULU MODEREN' => 'SEBULU MODEREN',
                                'MEKAR JAYA' => 'MEKAR JAYA',
                                'SELERONG' => 'SELERONG',
                                'SENONI' => 'SENONI',
                                'GIRI AGUNG' => 'GIRI AGUNG',
                                'BELORO' => 'BELORO',
                                'SEGIHAN' => 'SEGIHAN',
                                'TANJUNG HARAPAN' => 'TANJUNG HARAPAN',
                                'SANGGULAN' => 'SANGGULAN',
                                'LEKAQ KIDAU' => 'LEKAQ KIDAU',
                            ],
                            ['KUTAI KERTANEGARA', 'TABANG'] => [
                                'BILA TALANG' => 'BILA TALANG',
                                'GUNUNG SARI' => 'GUNUNG SARI',
                                'MUARA RITAN' => 'MUARA RITAN',
                                'MUARA PEDOHON' => 'MUARA PEDOHON',
                                'SIDOMULYO' => 'SIDOMULYO',
                                'KAMPUNG BARU' => 'KAMPUNG BARU',
                                'TUKUNG RITAN' => 'TUKUNG RITAN',
                                'RITAN BARU' => 'RITAN BARU',
                                'UMAQ DIAN' => 'UMAQ DIAN',
                                'BULUK SEN' => 'BULUK SEN',
                                'LONG LALANG' => 'LONG LALANG',
                                'MUARA TIQ' => 'MUARA TIQ',
                                'MUARA SALUNG' => 'MUARA SALUNG',
                                'MUARA TUBOQ' => 'MUARA TUBOQ',
                                'MUARA BELINAU' => 'MUARA BELINAU',
                                'MUARA KEBAQ' => 'MUARA KEBAQ',
                                'UMAQ TUKUNG' => 'UMAQ TUKUNG',
                                'UMAQ BEKUAY' => 'UMAQ BEKUAY',
                                'TABANG LAMA' => 'TABANG LAMA',
                            ],
                            ['KUTAI KERTANEGARA', 'TENGGARONG'] => [
                                'RAMPAK LAMBUR' => 'RAMPAK LAMBUR',
                                'BENDANG RAYA' => 'BENDANG RAYA',
                                'BUKIT BIRU' => 'BUKIT BIRU',
                                'JAHAB' => 'JAHAB',
                                'KAMPUNG BARU' => 'KAMPUNG BARU',
                                'LOA IPUH' => 'LOA IPUH',
                                'LOA IPUH DARAT' => 'LOA IPUH DARAT',
                                'LOA TEBU' => 'LOA TEBU',
                                'MALUHU' => 'MALUHU',
                                'MANGKURAWANG' => 'MANGKURAWANG',
                                'MELAYU' => 'MELAYU',
                                'PANJI' => 'PANJI',
                                'SUKARAME' => 'SUKARAME',
                                'TIMBAU' => 'TIMBAU',
                            ],
                            ['KUTAI KERTANEGARA', 'TENGGARONG SEBERANG'] => [
                                'MANUNGGAL JAYA' => 'MANUNGGAL JAYA',
                                'BANGUN REJO' => 'BANGUN REJO',
                                'BUANA JAYA' => 'BUANA JAYA',
                                'BUKIT RAYA' => 'BUKIT RAYA',
                                'SUKA MAJU' => 'SUKA MAJU',
                                'KARANG TUNGGAL' => 'KARANG TUNGGAL',
                                'EMBALUT' => 'EMBALUT',
                                'BUKIT PARIAMAN' => 'BUKIT PARIAMAN',
                                'PERJIWA' => 'PERJIWA',
                                'MULAWARMAN' => 'MULAWARMAN',
                                'LOA PARI' => 'LOA PARI',
                                'KERTA BUANA' => 'KERTA BUANA',
                                'TELUK DALAM' => 'TELUK DALAM',
                                'LOA ULUNG' => 'LOA ULUNG',
                                'LOA RAYA' => 'LOA RAYA',
                                'LOA LEPU' => 'LOA LEPU',
                                'SEPARI' => 'SEPARI',
                                'TANJUNG BATU' => 'TANJUNG BATU',
                            ],
                            ['KUTAI TIMUR', 'BATU AMPAR'] => [
                                'BATU TIMBAU' => 'BATU TIMBAU',
                                'BATU TIMBAU ULU' => 'BATU TIMBAU ULU',
                                'BENO HARAPAN' => 'BENO HARAPAN',
                                'HIMBA LESTARI' => 'HIMBA LESTARI',
                                'MAWAI INDAH' => 'MAWAI INDAH',
                                'MUGI RAHAYU' => 'MUGI RAHAYU',
                                'TELAGA' => 'TELAGA',
                            ],
                            ['KUTAI TIMUR', 'BENGALON'] => [
                                'KERAITAN' => 'KERAITAN',
                                'MUARA BENGALON' => 'MUARA BENGALON',
                                'SEKERAT' => 'SEKERAT',
                                'SEPASO' => 'SEPASO',
                                'SEPASO BARAT' => 'SEPASO BARAT',
                                'SEPASO INDUK' => 'SEPASO INDUK',
                                'SEPASO SELATAN' => 'SEPASO SELATAN',
                                'SEPASO TIMUR' => 'SEPASO TIMUR',
                                'TEBANGAN LEMBAK' => 'TEBANGAN LEMBAK',
                                'TEPIAN BARU' => 'TEPIAN BARU',
                                'TEPIAN BUDAYA' => 'TEPIAN BUDAYA',
                                'TEPIAN INDAH' => 'TEPIAN INDAH',
                                'TEPIAN LANGSAT' => 'TEPIAN LANGSAT',
                                'TEPIAN MADANI' => 'TEPIAN MADANI',
                                'TEPIAN RAYA' => 'TEPIAN RAYA',
                            ],
                            ['KUTAI TIMUR', 'BUSANG'] => [
                                'LONG BENTUQ' => 'LONG BENTUQ',
                                'LONG LEES' => 'LONG LEES',
                                'LONG NYELONG' => 'LONG NYELONG',
                                'LONG PEJENG' => 'LONG PEJENG',
                                'MEKAR BARU' => 'MEKAR BARU',
                                'RANTAU SENTOSA' => 'RANTAU SENTOSA',
                            ],
                            ['KUTAI TIMUR', 'KALIORANG'] => [
                                'BANGUN JAYA' => 'BANGUN JAYA',
                                'BUKIT HARAPAN' => 'BUKIT HARAPAN',
                                'BUKIT MAKMUR' => 'BUKIT MAKMUR',
                                'BUMI SEJAHTERA' => 'BUMI SEJAHTERA',
                                'CITRA MANUNGGAL JAYA' => 'CITRA MANUNGGAL JAYA',
                                'KALIORANG' => 'KALIORANG',
                                'SELANGKAU' => 'SELANGKAU',
                            ],
                            ['KUTAI TIMUR', 'KARANGAN'] => [
                                'BAAY' => 'BAAY',
                                'BATU LEPOQ' => 'BATU LEPOQ',
                                'KARANGAN DALAM' => 'KARANGAN DALAM',
                                'KARANGAN HILIR' => 'KARANGAN HILIR',
                                'KARANGAN SEBERANG' => 'KARANGAN SEBERANG',
                                'MUKTI LESTARI' => 'MUKTI LESTARI',
                                'PENGADAN' => 'PENGADAN',
                            ],
                            ['KUTAI TIMUR', 'KAUBUN'] => [
                                'BUKIT PERMATA' => 'BUKIT PERMATA',
                                'BUMI ETAM' => 'BUMI ETAM',
                                'BUMI JAYA' => 'BUMI JAYA',
                                'BUMI RAPAK' => 'BUMI RAPAK',
                                'CIPTA GRAHA' => 'CIPTA GRAHA',
                                'KADUNGAN JAYA' => 'KADUNGAN JAYA',
                                'MATA AIR' => 'MATA AIR',
                                'PENGADAN BARU' => 'PENGADAN BARU',
                            ],
                            ['KUTAI TIMUR', 'KOMBENG'] => [
                                'KOMBENG INDAH' => 'KOMBENG INDAH',
                                'MAKMUR JAYA' => 'MAKMUR JAYA',
                                'MARGA MULYA' => 'MARGA MULYA',
                                'MIAU BARU' => 'MIAU BARU',
                                'MIAU BARU UTARA' => 'MIAU BARU UTARA',
                                'SIDOMULYO' => 'SIDOMULYO',
                                'SRI PANTUN' => 'SRI PANTUN',
                                'SUKAMAJU' => 'SUKAMAJU',
                            ],
                            ['KUTAI TIMUR', 'LONG MESANGAT'] => [
                                'MELAN' => 'MELAN',
                                'MUKTI UTAMA' => 'MUKTI UTAMA',
                                'SEGOY MAKMUR' => 'SEGOY MAKMUR',
                                'SIKA MAKMUR' => 'SIKA MAKMUR',
                                'SUMBER AGUNG' => 'SUMBER AGUNG',
                                'SUMBER SARI' => 'SUMBER SARI',
                                'TANAH ABANG' => 'TANAH ABANG',
                            ],
                            ['KUTAI TIMUR', 'MUARA ANCALONG'] => [
                                'GEMAR BARU' => 'GEMAR BARU',
                                'KELINJAU ILIR' => 'KELINJAU ILIR',
                                'KELINJAU ULU' => 'KELINJAU ULU',
                                'LONG NAH' => 'LONG NAH',
                                'LONG POQ BARU' => 'LONG POQ BARU',
                                'LONG TESAK' => 'LONG TESAK',
                                'MUARA DUN' => 'MUARA DUN',
                                'SENYIUR' => 'SENYIUR',
                                'TELUK BARU' => 'TELUK BARU',
                            ],
                            ['KUTAI TIMUR', 'MUARA BENGKAL'] => [
                                'BATU BALAI' => 'BATU BALAI',
                                'BENUA BARU' => 'BENUA BARU',
                                'MUARA BENGKAL ILIR' => 'MUARA BENGKAL ILIR',
                                'MUARA BENGKAL ULU' => 'MUARA BENGKAL ULU',
                                'MULUPAN' => 'MULUPAN',
                                'NGAYAU' => 'NGAYAU',
                                'PARIANUM' => 'PARIANUM',
                                'SENAMBAH' => 'SENAMBAH',
                            ],
                            ['KUTAI TIMUR', 'MUARA WAHAU'] => [
                                'BENHES' => 'BENHES',
                                'DABEQ' => 'DABEQ',
                                'DIAQ LAY' => 'DIAQ LAY',
                                'JABDAN' => 'JABDAN',
                                'JAK LUAY' => 'JAK LUAY',
                                'KARYA BHAKTI' => 'KARYA BHAKTI',
                                'LONG WEHEA' => 'LONG WEHEA',
                                'MUARA WAHAU' => 'MUARA WAHAU',
                                'NEHES LIAH BING' => 'NEHES LIAH BING',
                                'WAHAU BARU' => 'WAHAU BARU',
                                'WANASARI' => 'WANASARI',
                            ],
                            ['KUTAI TIMUR', 'RANTAU PULUNG'] => [
                                'KEBON AGUNG' => 'KEBON AGUNG',
                                'MANUNGGAL JAYA' => 'MANUNGGAL JAYA',
                                'MARGO MULYO' => 'MARGO MULYO',
                                'MASALAP RAYA' => 'MASALAP RAYA',
                                'MUKTI JAYA' => 'MUKTI JAYA',
                                'PULUNG SARI' => 'PULUNG SARI',
                                'RANTAU MAKMUR' => 'RANTAU MAKMUR',
                                'TANJUNG LABU' => 'TANJUNG LABU',
                                'TEPIAN MAKMUR' => 'TEPIAN MAKMUR',
                            ],
                            ['KUTAI TIMUR', 'SANDARAN'] => [
                                'MANUBAR' => 'MANUBAR',
                                'MANUBAR DALAM' => 'MANUBAR DALAM',
                                'MARUKANGAN' => 'MARUKANGAN',
                                'SANDARAN' => 'SANDARAN',
                                'SUSUK DALAM' => 'SUSUK DALAM',
                                'SUSUK LUAR' => 'SUSUK LUAR',
                                'SUSUK TENGAH' => 'SUSUK TENGAH',
                                'TADOAN' => 'TADOAN',
                                'TANJUNG MANGKALIAT' => 'TANJUNG MANGKALIAT',
                            ],
                            ['KUTAI TIMUR', 'SANGATTA SELATAN'] => [
                                'SANGATTA SELATAN' => 'SANGATTA SELATAN',
                                'SANGKIMA' => 'SANGKIMA',
                                'SANGKIMA LAMA' => 'SANGKIMA LAMA',
                                'SINGA GEWEH' => 'SINGA GEWEH',
                            ],
                            ['KUTAI TIMUR', 'SANGATTA UTARA'] => [
                                'SANGATTA UTARA' => 'SANGATTA UTARA',
                                'SINGA GEMBARA' => 'SINGA GEMBARA',
                                'SWARGA BARA' => 'SWARGA BARA',
                                'TELUK LINGGA' => 'TELUK LINGGA',
                            ],
                            ['KUTAI TIMUR', 'SANGKULIRANG'] => [
                                'BENUA BARU ILIR' => 'BENUA BARU ILIR',
                                'BENUA BARU ULU' => 'BENUA BARU ULU',
                                'KERAYAAN' => 'KERAYAAN',
                                'KOLEK' => 'KOLEK',
                                'MALOY' => 'MALOY',
                                'MANDU DALAM' => 'MANDU DALAM',
                                'MANDU PANTAI SEJAHTERA' => 'MANDU PANTAI SEJAHTERA',
                                'PELAWAN' => 'PELAWAN',
                                'PERIDAN' => 'PERIDAN',
                                'PERUPUK' => 'PERUPUK',
                                'PULAU MIANG' => 'PULAU MIANG',
                                'SAKA' => 'SAKA',
                                'SEMPAYAU' => 'SEMPAYAU',
                                'TANJUNG MANIS' => 'TANJUNG MANIS',
                                'TEPIAN TERAP' => 'TEPIAN TERAP',
                            ],
                            ['KUTAI TIMUR', 'TELEN'] => [
                                'JUK AYAQ' => 'JUK AYAQ',
                                'KERNYANYAN' => 'KERNYANYAN',
                                'LONG NORAN' => 'LONG NORAN',
                                'LONG SEGAR' => 'LONG SEGAR',
                                'LUNG MELAH' => 'LUNG MELAH',
                                'MARAH HALOQ' => 'MARAH HALOQ',
                                'MUARA PANTUN' => 'MUARA PANTUN',
                                'RANTAU PANJANG' => 'RANTAU PANJANG',
                            ],
                            ['KUTAI TIMUR', 'TELUK PANDAN'] => [
                                'BUKIT PANDAN JAYA' => 'BUKIT PANDAN JAYA',
                                'DANAU REDAN' => 'DANAU REDAN',
                                'KANDOLO' => 'KANDOLO',
                                'MARTADINATA' => 'MARTADINATA',
                                'SUKA DAMAI' => 'SUKA DAMAI',
                                'SUKA RAHMAT' => 'SUKA RAHMAT',
                                'TELUK PANDAN' => 'TELUK PANDAN',
                            ],
                            ['MAHAKAM ULU', 'LAHAM'] => [
                                'LAHAM' => 'LAHAM',
                                'DANUM PAROY' => 'DANUM PAROY',
                                'LONG GELAWANG' => 'LONG GELAWANG',
                                'MUARA RATAH' => 'MUARA RATAH',
                                'NYARIBUNGAN' => 'NYARIBUNGAN',
                            ],
                            ['MAHAKAM ULU', 'LONG APARI'] => [
                                'LONG KERIOQ' => 'LONG KERIOQ',
                                'TIONG OHANG' => 'TIONG OHANG',
                                'TIONG BU\'U' => 'TIONG BU\'U',
                                'LONG PENANEH III' => 'LONG PENANEH III',
                                'LONG PENANEH I' => 'LONG PENANEH I',
                                'NAHA BUAN' => 'NAHA BUAN',
                                'LONG PENANEH II' => 'LONG PENANEH II',
                                'LONG APARI' => 'LONG APARI',
                                'NAHA SILAT' => 'NAHA SILAT',
                                'NAHA TIFAB' => 'NAHA TIFAB',
                            ],
                            ['MAHAKAM ULU', 'LONG BAGUN'] => [
                                'LONG BAGUN ULU' => 'LONG BAGUN ULU',
                                'MEMAHAK BESAR' => 'MEMAHAK BESAR',
                                'UJOH BILANG' => 'UJOH BILANG',
                                'MEMAHAK ULU' => 'MEMAHAK ULU',
                                'LONG MELAHAM' => 'LONG MELAHAM',
                                'BATOQ KELO' => 'BATOQ KELO',
                                'RUKUN DAMAI' => 'RUKUN DAMAI',
                                'LONG BAGUN ILIR' => 'LONG BAGUN ILIR',
                                'LONG MERAH' => 'LONG MERAH',
                                'BATU MAJANG' => 'BATU MAJANG',
                                'LONG HURAI' => 'LONG HURAI',
                            ],
                            ['MAHAKAM ULU', 'LONG HUBUNG'] => [
                                'DATAH BILANG ULU' => 'DATAH BILANG ULU',
                                'DATAH BILANG ILIR' => 'DATAH BILANG ILIR',
                                'DATAH BILANG BARU' => 'DATAH BILANG BARU',
                                'LUTAN' => 'LUTAN',
                                'MATALIBAQ' => 'MATALIBAQ',
                                'MEMAHAK TEBOQ' => 'MEMAHAK TEBOQ',
                                'LONG HUBUNG' => 'LONG HUBUNG',
                                'LONG HUBUNG ULU' => 'LONG HUBUNG ULU',
                                'SIRAU' => 'SIRAU',
                                'TRI PARIQ MAKMUR' => 'TRI PARIQ MAKMUR',
                                'WANA PARIQ' => 'WANA PARIQ',
                            ],
                            ['MAHAKAM ULU', 'LONG PAHANGAI'] => [
                                'LONG LUNUK BARU' => 'LONG LUNUK BARU',
                                'LONG ISUN' => 'LONG ISUN',
                                'LONG PAHANGAI I' => 'LONG PAHANGAI I',
                                'NAHA ARU' => 'NAHA ARU',
                                'LONG LUNUK' => 'LONG LUNUK',
                                'LONG PAHANGAI II' => 'LONG PAHANGAI II',
                                'LONG TUYOQ' => 'LONG TUYOQ',
                                'LIU MULANG' => 'LIU MULANG',
                                'DATAH NAHA' => 'DATAH NAHA',
                                'LONG PAKAQ BARU' => 'LONG PAKAQ BARU',
                                'DELANG KEROHONG' => 'DELANG KEROHONG',
                                'LIRUNG UBING' => 'LIRUNG UBING',
                                'LONG PAKAQ' => 'LONG PAKAQ',
                            ],
                            ['PASER', 'BATU ENGAU'] => [
                                'KERANG' => 'KERANG',
                                'TAMPAKAN' => 'TAMPAKAN',
                                'MENGKUDU' => 'MENGKUDU',
                                'TEBRU PASER DAMAI' => 'TEBRU PASER DAMAI',
                                'KERANG DAYO' => 'KERANG DAYO',
                                'SAING PRUPUK' => 'SAING PRUPUK',
                                'RIWANG' => 'RIWANG',
                                'SEGENDANG' => 'SEGENDANG',
                                'PETANGIS' => 'PETANGIS',
                                'LANGGAI' => 'LANGGAI',
                                'LOMU' => 'LOMU',
                                'PENGGUREN JAYA' => 'PENGGUREN JAYA',
                                'BAI JAYA' => 'BAI JAYA',
                            ],
                            ['PASER', 'BATU SOPANG'] => [
                                'BATU KAJANG' => 'BATU KAJANG',
                                'SONGKA' => 'SONGKA',
                                'SUNGAI TERIK' => 'SUNGAI TERIK',
                                'KASUNGAI' => 'KASUNGAI',
                                'LEGAI' => 'LEGAI',
                                'BUSUI' => 'BUSUI',
                                'SAMURANGGAU' => 'SAMURANGGAU',
                                'RANTAU BUTA' => 'RANTAU BUTA',
                                'RANTAU LAYUNG' => 'RANTAU LAYUNG',
                            ],
                            ['PASER', 'KUARO'] => [
                                'KENDAROM' => 'KENDAROM',
                                'KELUANG LOLO' => 'KELUANG LOLO',
                                'KELUANG PASER JAYA' => 'KELUANG PASER JAYA',
                                'KERTA BUMI' => 'KERTA BUMI',
                                'MODANG' => 'MODANG',
                                'PONDANG BARU' => 'PONDANG BARU',
                                'PASIR MAYANG' => 'PASIR MAYANG',
                                'PADANG JAYA' => 'PADANG JAYA',
                                'KLEMPANG SARI' => 'KLEMPANG SARI',
                                'HARAPAN BARU' => 'HARAPAN BARU',
                                'SANDELEY' => 'SANDELEY',
                                'RANGAN' => 'RANGAN',
                                'KUARO' => 'KUARO',
                            ],
                            ['PASER', 'LONG IKIS'] => [
                                'SAMUNTAI' => 'SAMUNTAI',
                                'PAIT' => 'PAIT',
                                'TAJUR' => 'TAJUR',
                                'JEMPARING' => 'JEMPARING',
                                'ATANG PAIT' => 'ATANG PAIT',
                                'BUKIT SALOKA' => 'BUKIT SALOKA',
                                'KRAYAN MAKMUR' => 'KRAYAN MAKMUR',
                                'SAWIT JAYA' => 'SAWIT JAYA',
                                'KRAYAN JAYA' => 'KRAYAN JAYA',
                                'LOMBOK' => 'LOMBOK',
                                'KERTA BHAKTI' => 'KERTA BHAKTI',
                                'KRAYAN SENTOSA' => 'KRAYAN SENTOSA',
                                'KRAYAN BAHAGIA' => 'KRAYAN BAHAGIA',
                                'ADANG JAYA' => 'ADANG JAYA',
                                'TELUK WARU' => 'TELUK WARU',
                                'OLUNG' => 'OLUNG',
                                'KAYUNGO' => 'KAYUNGO',
                                'TAJER MULYA' => 'TAJER MULYA',
                                'TIWEI' => 'TIWEI',
                                'SEKUROU JAYA' => 'SEKUROU JAYA',
                                'MUARA ADANG' => 'MUARA ADANG',
                                'KAYUNGO SARI' => 'KAYUNGO SARI',
                                'BELIMBING' => 'BELIMBING',
                                'BREWE' => 'BREWE',
                                'LONG GELANG' => 'LONG GELANG',
                                'LONG IKIS' => 'LONG IKIS',
                            ],
                            ['PASER', 'LONG KALI'] => [
                                'MAKMUR JAYA' => 'MAKMUR JAYA',
                                'PUTANG' => 'PUTANG',
                                'MENDIK' => 'MENDIK',
                                'GUNUNG PUTAR' => 'GUNUNG PUTAR',
                                'MENDIK MAKMUR' => 'MENDIK MAKMUR',
                                'MUARA TELAKE' => 'MUARA TELAKE',
                                'SEBAKUNG TAKA' => 'SEBAKUNG TAKA',
                                'SEBAKUNG' => 'SEBAKUNG',
                                'MARUAT' => 'MARUAT',
                                'MENDIK KARYA' => 'MENDIK KARYA',
                                'BENTE TUALAN' => 'BENTE TUALAN',
                                'SEBAKUNG MAKMUR' => 'SEBAKUNG MAKMUR',
                                'MENDIK BHAKTI' => 'MENDIK BHAKTI',
                                'MUARA PIAS' => 'MUARA PIAS',
                                'PINANG JATUS' => 'PINANG JATUS',
                                'MUNGGU' => 'MUNGGU',
                                'PETIKU' => 'PETIKU',
                                'PERKUWEN' => 'PERKUWEN',
                                'MUARA LAMBAKAN' => 'MUARA LAMBAKAN',
                                'MUARA TOYU' => 'MUARA TOYU',
                                'MUARA ADANG II' => 'MUARA ADANG II',
                                'KEPALA TELAKE' => 'KEPALA TELAKE',
                                'LONG KALI' => 'LONG KALI',
                            ],
                            ['PASER', 'MUARA KOMAM'] => [
                                'MUARA LANGON' => 'MUARA LANGON',
                                'BATU BUTOK' => 'BATU BUTOK',
                                'SELERONG' => 'SELERONG',
                                'MUARA KUARO' => 'MUARA KUARO',
                                'UKO' => 'UKO',
                                'SEKUAN MAKMUR' => 'SEKUAN MAKMUR',
                                'MUARA PAYANG' => 'MUARA PAYANG',
                                'SWAN SLUTUNG' => 'SWAN SLUTUNG',
                                'BINANGON' => 'BINANGON',
                                'PRAYON' => 'PRAYON',
                                'LONG SAYO' => 'LONG SAYO',
                                'LUSAN' => 'LUSAN',
                                'MUARA KOMAM' => 'MUARA KOMAM',
                            ],
                            ['PASER', 'MUARA SAMU'] => [
                                'MUSER' => 'MUSER',
                                'LIBUR DINDING' => 'LIBUR DINDING',
                                'BIU' => 'BIU',
                                'RANTAU ATAS' => 'RANTAU ATAS',
                                'LUAN' => 'LUAN',
                                'SUWETO' => 'SUWETO',
                                'TANJUNG PINANG' => 'TANJUNG PINANG',
                                'RANTAU BINTUNGAN' => 'RANTAU BINTUNGAN',
                                'MUARA ANDEH' => 'MUARA ANDEH',
                            ],
                            ['PASER', 'PASER BELENGKONG'] => [
                                'PASIR BELENGKONG' => 'PASIR BELENGKONG',
                                'SULILIRAN BARU' => 'SULILIRAN BARU',
                                'LABURAN BARU' => 'LABURAN BARU',
                                'LABURAN' => 'LABURAN',
                                'KERESIK BURA' => 'KERESIK BURA',
                                'LEMPESU' => 'LEMPESU',
                                'SUATANG KETEBAN' => 'SUATANG KETEBAN',
                                'DAMIT' => 'DAMIT',
                                'SANGKURIMAN' => 'SANGKURIMAN',
                                'SUATANG' => 'SUATANG',
                                'BEKOSO' => 'BEKOSO',
                                'OLONG PINANG' => 'OLONG PINANG',
                                'SUNGE BATU' => 'SUNGE BATU',
                                'SENIUNG JAYA' => 'SENIUNG JAYA',
                                'SULILIRAN' => 'SULILIRAN',
                            ],
                            ['PASER', 'TANAH GROGOT'] => [
                                'PADANG PENGRAPAT' => 'PADANG PENGRAPAT',
                                'JANJU' => 'JANJU',
                                'SENAKEN' => 'SENAKEN',
                                'TAPIS' => 'TAPIS',
                                'SEMPULANG' => 'SEMPULANG',
                                'RANTAU PANJANG' => 'RANTAU PANJANG',
                                'SUNGAI TUAK' => 'SUNGAI TUAK',
                                'TEPIAN BATANG' => 'TEPIAN BATANG',
                                'MUARA PASIR' => 'MUARA PASIR',
                                'TANAH PERIUK' => 'TANAH PERIUK',
                                'JONE' => 'JONE',
                                'PEPARA' => 'PEPARA',
                                'PULAU RANTAU' => 'PULAU RANTAU',
                                'SUNGAI LANGIR' => 'SUNGAI LANGIR',
                                'PEREPAT' => 'PEREPAT',
                                'TANAH GROGOT' => 'TANAH GROGOT',
                            ],
                            ['PASER', 'TANJUNG ARU'] => [
                                'TANJUNG ARU' => 'TANJUNG ARU',
                                'LORI' => 'LORI',
                                'KELADEN' => 'KELADEN',
                                'SENIPAH' => 'SENIPAH',
                                'RANDOM' => 'RANDOM',
                                'SELENGOT' => 'SELENGOT',
                                'LABUANGKALLO' => 'LABUANGKALLO',
                            ],
                            ['PENAJAM PASER UTARA', 'BABULU'] => [
                                'BABULU DARAT' => 'BABULU DARAT',
                                'GUNUNG MULIA' => 'GUNUNG MULIA',
                                'SUMBER SARI' => 'SUMBER SARI',
                                'LABANGKA BARAT' => 'LABANGKA BARAT',
                                'SRI RAHARJA' => 'SRI RAHARJA',
                                'LABANGKA' => 'LABANGKA',
                                'RAWA MULIA' => 'RAWA MULIA',
                                'GUNUNG MAKMUR' => 'GUNUNG MAKMUR',
                                'GUNUNG INTAN' => 'GUNUNG INTAN',
                                'SEBAKUNG JAYA' => 'SEBAKUNG JAYA',
                                'RINTIK' => 'RINTIK',
                                'BABULU LAUT' => 'BABULU LAUT',
                            ],
                            ['PENAJAM PASER UTARA', 'PENAJAM'] => [
                                'GIRI MUKTI' => 'GIRI MUKTI',
                                'SIDOREJO' => 'SIDOREJO',
                                'GIRI PURWA' => 'GIRI PURWA',
                                'BUKIT SUBUR' => 'BUKIT SUBUR',
                                'BULUMINUNG' => 'BULUMINUNG',
                                'GERSIK' => 'GERSIK',
                                'GUNUNG SETELEN' => 'GUNUNG SETELEN',
                                'JENEBORA' => 'JENEBORA',
                                'KAMPUNG BARU' => 'KAMPUNG BARU',
                                'LAWE-LAWE' => 'LAWE-LAWE',
                                'NENANG' => 'NENANG',
                                'NIPAH-NIPAH' => 'NIPAH-NIPAH',
                                'PANTAI LANGO' => 'PANTAI LANGO',
                                'PEJALA' => 'PEJALA',
                                'PENAJAM' => 'PENAJAM',
                                'PETUNG' => 'PETUNG',
                                'RIKO' => 'RIKO',
                                'SALO LOANG' => 'SALO LOANG',
                                'SEPAN' => 'SEPAN',
                                'SESUMPU' => 'SESUMPU',
                                'SOTEK' => 'SOTEK',
                                'SUNGAI PARIT' => 'SUNGAI PARIT',
                                'TANJUNG TENGAH' => 'TANJUNG TENGAH',
                            ],
                            ['PENAJAM PASER UTARA', 'SEPAKU'] => [
                                'SUKA RAJA' => 'SUKA RAJA',
                                'SEMOI DUA' => 'SEMOI DUA',
                                'TENGIN BARU' => 'TENGIN BARU',
                                'ARGO MULYO' => 'ARGO MULYO',
                                'SUKO MULYO' => 'SUKO MULYO',
                                'TELEMOW' => 'TELEMOW',
                                'BUKIT RAYA' => 'BUKIT RAYA',
                                'WONO SARI' => 'WONO SARI',
                                'BINUANG' => 'BINUANG',
                                'BUMI HARAPAN' => 'BUMI HARAPAN',
                                'KARANG JINAWI' => 'KARANG JINAWI',
                                'MARIDAN' => 'MARIDAN',
                                'MENTAWIR' => 'MENTAWIR',
                                'PEMALUAN' => 'PEMALUAN',
                                'SEPAKU' => 'SEPAKU',
                            ],
                            ['PENAJAM PASER UTARA', 'WARU'] => [
                                'BANGUN MULYA' => 'BANGUN MULYA',
                                'SESULU' => 'SESULU',
                                'API-API' => 'API-API',
                                'WARU' => 'WARU',
                            ],
                            ['SAMARINDA', 'LOA JANAN ILIR'] => [
                                'HARAPAN BARU' => 'HARAPAN BARU',
                                'RAPAK DALAM' => 'RAPAK DALAM',
                                'SENGKOTEK' => 'SENGKOTEK',
                                'SIMPANG TIGA' => 'SIMPANG TIGA',
                                'TANI AMAN' => 'TANI AMAN',
                            ],
                            ['SAMARINDA', 'PALARAN'] => [
                                'BANTUAS' => 'BANTUAS',
                                'BUKUAN' => 'BUKUAN',
                                'HANDIL BAKTI' => 'HANDIL BAKTI',
                                'RAWA MAKMUR' => 'RAWA MAKMUR',
                                'SIMPANG PASIR' => 'SIMPANG PASIR',
                            ],
                            ['SAMARINDA', 'SAMARINDA ILIR'] => [
                                'PELITA' => 'PELITA',
                                'SELILI' => 'SELILI',
                                'SIDODAMAI' => 'SIDODAMAI',
                                'SIDOMULYO' => 'SIDOMULYO',
                                'SUNGAI DAMA' => 'SUNGAI DAMA',
                            ],
                            ['SAMARINDA', 'SAMARINDA KOTA'] => [
                                'BUGIS' => 'BUGIS',
                                'KARANG MUMUS' => 'KARANG MUMUS',
                                'PASAR PAGI' => 'PASAR PAGI',
                                'PELABUHAN' => 'PELABUHAN',
                                'SUNGAI PINANG LUAR' => 'SUNGAI PINANG LUAR',
                            ],
                            ['SAMARINDA', 'SAMARINDA SEBERANG'] => [
                                'BAQA' => 'BAQA',
                                'GUNUNG PANJANG' => 'GUNUNG PANJANG',
                                'MANGKUPALAS' => 'MANGKUPALAS',
                                'MESJID' => 'MESJID',
                                'SUNGAI KELEDANG' => 'SUNGAI KELEDANG',
                                'TENUN' => 'TENUN',
                            ],
                            ['SAMARINDA', 'SAMARINDA ULU'] => [
                                'AIR HITAM' => 'AIR HITAM',
                                'AIR PUTIH' => 'AIR PUTIH',
                                'BUKIT PINANG' => 'BUKIT PINANG',
                                'DADI MULYA' => 'DADI MULYA',
                                'GUNUNG KELUA' => 'GUNUNG KELUA',
                                'JAWA' => 'JAWA',
                                'SIDODADI' => 'SIDODADI',
                                'TELUK LERONG ILIR' => 'TELUK LERONG ILIR',
                            ],
                            ['SAMARINDA', 'SAMARINDA UTARA'] => [
                                'BUDAYA PAMPANG' => 'BUDAYA PAMPANG',
                                'LEMPAKE' => 'LEMPAKE',
                                'SEMPAJA BARAT' => 'SEMPAJA BARAT',
                                'SEMPAJA UTARA' => 'SEMPAJA UTARA',
                                'SEMPAJA SELATAN' => 'SEMPAJA SELATAN',
                                'SEMPAJA TIMUR' => 'SEMPAJA TIMUR',
                                'SUNGAI SIRING' => 'SUNGAI SIRING',
                                'TANAH MERAH' => 'TANAH MERAH',
                            ],
                            ['SAMARINDA', 'SAMBUTAN'] => [
                                'MAKROMAN' => 'MAKROMAN',
                                'PULAU ATAS' => 'PULAU ATAS',
                                'SAMBUTAN' => 'SAMBUTAN',
                                'SINDANG SARI' => 'SINDANG SARI',
                                'SUNGAI KAPIH' => 'SUNGAI KAPIH',
                            ],
                            ['SAMARINDA', 'SUNGAI KUNJANG'] => [
                                'LOA BUAH' => 'LOA BUAH',
                                'LOA BAKUNG' => 'LOA BAKUNG',
                                'LOA BAHU' => 'LOA BAHU',
                                'KARANG ANYAR' => 'KARANG ANYAR',
                                'KARANG ASAM ILIR' => 'KARANG ASAM ILIR',
                                'KARANG ASAM ULU' => 'KARANG ASAM ULU',
                                'TELUK LERONG ULU' => 'TELUK LERONG ULU',
                            ],
                            ['SAMARINDA', 'SUNGAI PINANG'] => [
                                'BANDARA' => 'BANDARA',
                                'GUNUNG LINGAI' => 'GUNUNG LINGAI',
                                'MUGIREJO' => 'MUGIREJO',
                                'SUNGAI PINANG DALAM' => 'SUNGAI PINANG DALAM',
                                'TEMINDUNG PERMAI' => 'TEMINDUNG PERMAI',
                            ],
                            default => [],
                        };
                    }),
                Forms\Components\TextInput::make('alamat')
                    ->required()
                    ->label('Alamat'),
                Forms\Components\TextInput::make('no_handphone')
                    ->required()
                    ->label('No. Whatsapp')
                    ->tel()
                    ->telRegex('/^[+]*[(]{0,1}[0-9]{1,4}[)]{0,1}[-\s\.\/0-9]*$/'),
                Forms\Components\Select::make('posisi')
                    ->required()
                    ->label('Posisi')
                    ->options([
                        'Relawan' => 'Relawan',
                    ])
                    ->hidden()
                    ->dehydrated(true),
                Forms\Components\TextInput::make('pengajak')
                    ->required()
                    ->label('Siapa yang mengajak?'),
                Forms\Components\Select::make('status')
                    ->required()
                    ->label('Status')
                    ->options([
                        'Proses' => 'Proses',
                        'Terverifikasi' => 'Terverifikasi'
                    ])
                    ->default('Proses')
                    ->disabled()
                    ->dehydrated(true)
            ])
            ->statePath('data')
            ->model(RelawanManual::class);
    }

    public function create(): void
    {
        $data = $this->form->getState();

        $record = RelawanManual::create($data);

        $this->form->model($record)->saveRelationships();

        Notification::make()
            ->success()
            ->title('Selamat! Anda telah terdaftar!')
            ->seconds(5)
            ->send();

        $this->form->fill();

        $this->redirect('/form-relawan');
    }

    public function render(): View
    {
        return view('livewire.daftar-form');
    }
}
